apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-test
  description: Python service created via Backstage
  annotations:
    github.com/project-slug: nishank841/python-test
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
