apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-testman
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nishank841/Helm-charts
    targetRevision: main
    path: base-app
    helm:
      valueFiles:
        - $values/apps/python-testman/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: python-testman-ns-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
